rockets/keppler_frontend/config/routes.rb
KepplerFrontend::Engine.routes.draw do
  root to: 'app/frontend#keppler', as: :keppler
  get '/form_events', to: 'app/frontend#form_events', as: :form_events
  get '/single_room', to: 'app/frontend#single_room', as: :single_room
  get '/gallery', to: 'app/frontend#gallery' 
  post '/reservaciones', to: 'app/frontend#create_reservation', as: 'create_reservation'

  #ajax find room
  get '/reservations/room/:room_id/:target_id', to: 'app/frontend#reservations_find_room', as: :reservations_find_room
    
  namespace :admin do
    scope :frontend, as: :frontend do
      resources :themes do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get '/show_covers', action: 'show_covers', as: 'show_covers'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      get '/views', to: 'views#index', as: 'views'
      post '/views/select_theme', to: 'views#select_theme', as: 'views_select_theme'
      get '/views/refresh', to: 'views#refresh', as: 'views_refresh'
      post '/views/generate', to: 'views#generate', as: 'views_generate'
      delete '/views/remove/:file', to: 'views#remove', as: 'views_remove'

      
      #post "/reservaciones" => 'app/frontend#create_reservations' , as: :create_reservation


      get '/assets', to: 'multimedia#index', as: 'multimedia'
      post '/assets/upload', to: 'multimedia#upload', as: 'upload_multimedia'
      get '/assets/upload', to: 'multimedia#upload', as: 'show_upload_multimedia'
      delete '/assets/:search/:fileformat', to: 'multimedia#destroy', as: 'destroy_multimedia'
      get '/assets/:search/:fileformat', to: 'multimedia#destroy', as: 'show_destroy_multimedia'

    end
  end
end

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/_new_view.html.haml
.new-view.modal.fade{id: "new-view", "aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  = simple_form_for "", url: admin_frontend_views_generate_path, remote: true, method: :post do |f|
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-header
          %h5#exampleModalLabel.modal-title= t('keppler.actions.new_view')
          %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
        .modal-body.clearfix
          %label= t('activerecord.attributes.name')
          = f.input_field :name, class: "form-control", placeholder: t('activerecord.attributes.name')
          %br
          %label= t('activerecord.attributes.url')
          = f.input_field :url, class: "form-control", placeholder: t('activerecord.attributes.url')
          %br
          %label= t('activerecord.attributes.method')
          = f.input_field :method, collection: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'], include_blank: false, class: "form-control"
          %br
          %label= t('activerecord.attributes.format')
          = f.input_field :view_format, collection: ['erb', 'haml'], include_blank: false, class: "form-control"
          %br
          #error-message
        .modal-footer
          = f.button :submit, t('keppler.actions.generate'), name: '_save', class: 'btn-primary'
          %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"}= t('keppler.actions.close')

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/_select_theme.html.haml
.asign-theme.modal.fade{id: "asign-theme-#{index}", "aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title= t('keppler_frontend.select_theme_view')
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body.clearfix
        - @resources.each_with_index do |file, i|
          .col-lg-4
            .box.box-solid
              .box-header.with-border{title: "#{file[:name]}"}
                .row
                  .col-lg-12
                    %h4.box-title
                      %i.fa.fa-tint
                      = truncate(file[:name].split('.').first, length: 30, omission: '...')
              .box-body.no-padding
                .back-file-xs{ style: "height: 160px;"}
                  .center
                    - if file[:cover].nil?
                      %i.fa.fa-tint#font-icon-size
                    - else
                      .theme-img{ style: "background-image: url(#{file[:cover]})" }
              .box-body
                %span.box-title
                  = file[:size]
                  = link_to admin_frontend_views_select_theme_path(view_format: view.first.split('.').last, view: view.first.to_s, theme: file[:path]), class: 'btn btn-default pull-right', method: :post, data: { confirm: t("keppler_frontend.select_view_confirm") } do
                    %i.fa.fa-check
          
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"}= t('keppler.actions.close')

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/_views_listing.html.haml
.box.slice-box
  .box-body.no-padding
    %table.table
      %thead
        - if views.size.zero?
          %tr
            %th{style: 'text-align: center;'}
              %h6= t('keppler.messages.not_found_records', model:  t("keppler_frontend.models.pluralize.views"))
        - else
          %tr
            %th.hidden-xs= t('activerecord.attributes.method')
            %th.hidden-xs= t('activerecord.attributes.route')
            %th.hidden-xs= t('activerecord.attributes.type')
            %th.hidden-xs= t('keppler_frontend.models.singularize.theme')
            %th.hidden-xs
      %tbody.objects-container
        - views.each_with_index do |view, i|
          - unless view.last.eql?('')
            %tr
              %td.hidden-xs{ style: "width: 10%"}
                = link_to "#", remote: true, class: 'show-row' do
                  %span.badge
                    = view.last.upcase
              %td
                = link_to "#", remote: true, class: 'show-row' do
                  %span
                    - if view.last.upcase.eql?('ROOT')
                      = '/'
                    - else
                      = view.second
              %td.hidden-xs{ style: "width: 10%"}
                = link_to "#", remote: true, class: 'show-row' do
                  %span
                    = view.first.split('.').last.capitalize
              %td{ style: "width: 10%"}
                = link_to "#", remote: true, class: 'show-row', title: t('keppler.actions.add_theme'), "data-toggle": "modal",  "data-target": "#asign-theme-#{i}" do
                  %span
                    %i.bx.bxs-magic-wand
              %td{ style: "width: 10%"}
                = link_to admin_frontend_views_remove_path(i), remote: true, method: :delete, class: 'show-row', title: t('keppler.actions.delete') do
                  %span
                    %i.bx.bx-trash
            = render 'select_theme', view: view, index: i

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/generate.js.erb
<%- if @error %>
  $('#error-message').html("<%= @error %>")
<%- else %>
  $('#error-message').html("");
  $('#new-view').modal('hide');
  $("#views-listing").html("<%= j render 'views_listing', views: @views %>");
<%- end %>

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/index.html.haml
.container
  %section.content-header.index-header
    %h1{ style: 'display: inline-block' }
      = t("keppler.actions.views")
  .row
    .col-lg-6
      .box.slice-box.box-preview.hidden-xs
        .box-header.with-border
          %h3.box-title= t('keppler.actions.preview')
          .box-tools.pull-right#tools
            %i.bx.bx-desktop#lg
            %i.bx.bx-tab#md
            %i.bx.bx-mobile#xs
            %i.bx.bx-revision#reload
        .box-body.box-body-no-padding.hidden-xs#box-body-bg
          #box-body
            %iframe.preview-iframe#preview.hidden-xs{ src: "#{request.base_url}" }
    .col-lg-6
      %section.content-actions
        .add
          = link_to "#", class: "btn-add", "data-toggle": "modal", "data-target": "#new-view" do
            +
            = t('keppler.actions.new_view')
          = link_to admin_frontend_views_refresh_path, remote: true, class: "btn btn-secondary" do
            %i.bx.bx-revision
            = t('keppler.actions.refresh')
      #views-listing
        = render 'views_listing', views: @views
= render 'new_view'

:javascript
  $(document).on("turbolinks:load",function(){
    $(document).ready(function() {
      $('#xs').click(function() {
        $('#box-body').animate({ 'width': '35%' }, 300)
      })

      $('#md').click(function() {
        $('#box-body').animate({ 'width': '70%' }, 300)
      })

      $('#lg').click(function() {
        $('#box-body').animate({ 'width': '100%' }, 300)
      })

      $('#reload').click(function() {
        var url = document.getElementById("preview").contentWindow.location.href
        $('iframe').attr('src', url)
      })
    });
  });

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/refresh.js.erb
$("#views-listing").html("<%= j render 'views_listing', views: @views %>")

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/remove.js.erb
  $("#views-listing").html("<%= j render 'views_listing', views: @views %>");