config/routes.rb
Rails.application.routes.draw do
  localized do
    get '/index', to: 'app/front#index', as: :app_index
  end

  # root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  post '/filter', to: 'admin/users#filter_by_role', as: :filter_by_role

  namespace :admin do
    root to: 'admin#root'

    namespace :rockets do
      get '/', action: :rockets
      post 'create/:rocket', action: :create, as: :create
      post 'install', action: :install
      post 'build/:rocket', action: :build, as: :build
      delete 'uninstall/:rocket', action: :uninstall, as: :uninstall
    end

    get '/seo/sitemap', to: 'seos#sitemap'
    get '/seo/robots', to: 'seos#robots'
    post '/seo/editor/save', to: 'seos#editor_save'

    resources :seos do
      post '/sort', action: :sort, on: :collection
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :roles do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      get '/download', action: 'download', as: :download
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
      # post '/show_description/:module/:action_name', action: 'show_description', as: :show_description
      # get(
      #   '/add_permissions',
      #   action: 'add_permissions',
      #   as: :add_permissions
      # )
      # post(
      #   '/create_permissions',
      #   action: 'create_permissions',
      #   as: :create_permissions
      # )
    end

    scope :roles do
      post(
        ':role_id/show_description/:module/:action_name',
        to: 'permissions#show',
        as: :role_show_description
      )
      get(
        ':role_id/add_permissions',
        to: 'permissions#add',
        as: :role_add_permissions
      )
      post(
        ':role_id/create_permissions',
        to: 'permissions#create',
        as: :role_create_permissions
      )
      post(
        ':role_id/toggle_permissions',
        to: 'permissions#toggle_permissions',
        as: :role_toggle_permissions
      )
    end

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/delete_avatar', action: :delete_avatar
      get(
        '/reload',
        action: :reload,
        on: :collection
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :scripts do
      get '(page/:page)', action: :index, on: :collection, as: ''
      get '/clone', action: 'clone'
      post '/upload', action: 'upload', as: :upload
      post(
        '/sort',
        action: :sort,
        on: :collection,
      )
      get(
        '/reload',
        action: :reload,
        on: :collection,
      )
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        post '/lang/:locale', to: 'settings#change_locale', as: :change_locale
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
        put '/:config/appearance_default', to: 'settings#appearance_default', as: 'appearance_default'
      end
    end
  end

  scope ":admin_code" do 
    devise_scope :user do
      get '/sign_in', to: 'devise/keppler_sessions#new'
      post '/sign_in', to: 'devise/keppler_sessions#create'
      delete '/sign_out', to: 'devise/keppler_sessions#destroy'
    end
  end

  # Errors routes
  match '/alert/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/alert/404', to: 'errors#not_found', via: :all
  match '/alert/422', to: 'errors#unprocessable', via: :all
  match '/alert/500', to: 'errors#internal_server_error', via: :all

  # Dashboard routes engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'

  # Frontend routes engine
  mount KepplerFrontend::Engine, at: '/', as: 'frontend'

  # Language routes engine
  mount KepplerLanguages::Engine, at: '/', as: 'languages'

  # Capsules routes engine
  mount KepplerCapsules::Engine, at: '/', as: 'capsules'

  # Ckeditor routes engine
  mount Ckeditor::Engine => '/ckeditor'

  # Home routes engine
  mount KepplerHome::Engine, at: '/', as: 'home'

  # Booking routes engine
  mount KepplerBooking::Engine, at: '/', as: 'booking' 
end

app/models/role.rb
# frozen_string_literal: true

# Role model
class Role < ApplicationRecord
  #
  # include Recoverable
  #
  # before_create -> { create_yml('role') }
  # # before_destroy -> { update_yml('role') }

  has_and_belongs_to_many :users, join_table: :users_roles
  belongs_to :resource,
             polymorphic: true,
             optional: true,
             dependent: :destroy
  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true
  scopify
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :permissions, dependent: :destroy

  def self.search_field
    :name_cont
  end

  # def destroy_yml_file
  #   destroy_yml('role')
  # end

  def permissions?
    !permissions.empty?
  end

  def all_permissions
    permissions.first&.modules
  end

  def permission_to(module_name)
    !all_permissions&.dig(module_name).nil? || false
  end

  def action?(module_name, action)
    permit = all_permissions
    return unless permit && !permit[module_name].nil?
    permit[module_name]['actions'].include?(action)
  end

  def include_actions?(module_name, actions)
    permit = all_permissions
    return unless permit && !permit[module_name].nil?
    permit[module_name]['actions'] & actions
  end

  def toggle_actions(module_name, action)
    if permission_to(module_name)
      update_action(module_name, action)
    else
      add_module(module_name, action)
    end
  end

  def toggle_all_actions(module_name, actions)
    if permission_to(module_name)
      update_actions(module_name, actions)
    else
      add_module(module_name, actions)
    end
  end

  def all_actions?(module_name, actions)
    return unless permission_to(module_name)
    permit = all_permissions[module_name]['actions'].reject(&:empty?)
    permit.blank? ? false : permit.uniq.length.eql?(actions&.uniq&.length)
  end

  def first_permission(module_name, action)
    Permission.create(
      role_id: id,
      modules: Hash[module_name, Hash['actions', Array(action)]]
    )
  end

  def add_module(module_name, action)
    old_hash = all_permissions
    new_hash = Hash[module_name, Hash['actions', Array(action)]]
    permissions.first.update(modules: old_hash.merge(new_hash))
  end

  private

  def add_action(module_name, action)
    permission = permissions.first
    permission.update(modules: create_hash('add', module_name, action))
  end

  def remove_action(module_name, action)
    permission = permissions.first
    permission.update(modules: create_hash('remove', module_name, action))
  end

  def update_action(module_name, action)
    if action?(module_name, action)
      remove_action(module_name, action)
    else
      add_action(module_name, action)
    end
  end

  def update_actions(module_name, actions)
    if all_actions?(module_name, actions) || actions.blank?
      clear_actions(module_name)
    else
      actions&.each { |act| add_action(module_name, act) }
    end
  end

  def clear_actions(module_name)
    old_hash = all_permissions
    new_hash = Hash[module_name, Hash['actions', []]]
    permissions.first.update(modules: old_hash.merge(new_hash))
  end

  def create_hash(act, module_name, action)
    old_hash = all_permissions
    arr = old_hash.dig(module_name, 'actions')

    act.eql?('add') ? arr.push(action) : arr.delete_if { |a| a.eql?(action) }

    new_hash = Hash[module_name, Hash['actions', arr]]
    old_hash.merge(new_hash)
  end
end

app/controllers/admin/roles_controller.rb
# frozen_string_literal: true

module Admin
  # RolesController
  class RolesController < AdminController
    before_action :set_role, only: %i[show edit update destroy]
    before_action :show_history, only: [:index]
    before_action :authorization, except: %i[reload]
    include ObjectQuery

    # GET /roles
    def index
      @q = Role.ransack(params[:q])
      @roles = @q.result(distinct: true)
      @roles = @roles.where.not(name: 'keppler_admin')
      @objects = @roles.page(@current_page).order(position: :desc)
      @total = @roles.size
      redirect_to_index(@objects)
      respond_to_formats(@roles)
    end

    # GET /roles/1
    def show; end

    # GET /roles/new
    def new
      @role = Role.new
    end

    # GET /roles/1/edit
    def edit; end

    # POST /roles
    def create
      @role = Role.new(role_params)

      if @role.save
        redirect_to admin_role_add_permissions_path(@role)
      else
        render :new
      end
    end

    # PATCH/PUT /roles/1
    def update
      if @role.update(role_params)
        redirect(@role, params)
      else
        render :edit
      end
    end

    def clone
      @role = Role.clone_record params[:role_id]
      if @role.save
        redirect_to admin_roles_path
      else
        render :new
      end
    end

    # DELETE /roles/1
    def destroy
      @role.destroy
      redirect_to admin_roles_path, notice: actions_messages(@role)
    end

    def destroy_multiple
      Role.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_roles_path(page: @current_page, search: @query),
        notice: actions_messages(Role.new)
      )
    end

    def upload
      Role.upload(params[:file])
      redirect_to(
        admin_roles_path(page: @current_page, search: @query),
        notice: actions_messages(Role.new)
      )
    end

    def download
      @roles = Role.all
      respond_to do |format|
        format.html
        format.xls { send_data(@roles.to_xls) }
        format.json { render json: @roles }
      end
    end

    def reload
      @q = Role.ransack(params[:q])
      roles = @q.result(distinct: true)
      @objects = roles.page(@current_page).order(position: :desc)
    end

    def sort
      Role.sorter(params[:row])
      render :index
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def role_params
      params.require(:role).permit(:name, :role_id)
    end

    def authorization
      authorize Role
    end

    def show_history
      get_history(Role)
    end
  end
end

app/helpers/roles_helper.rb
# frozen_string_literal: true

# RolesHelper
module RolesHelper
end

app/views/admin/roles/_description.html.haml
%aside.control-sidebar.control-sidebar-light
  .tab-content
    %p.control-sidebar-heading
      = activities.empty? ? t('keppler.messages.no_events') : t('keppler.titles.history')
    %ul.timeline
      - activities.each do |activity|
        - if activity.trackable_type.eql? 'Session'
          %li
            = render partial: "public_activity/session/#{activity.key.split('.').second}", locals: { activity: activity, method: 'id' }
        - else
          %li
            = render partial: "public_activity/layout/#{activity.key.split('.').second}", locals: { activity: activity, method: 'id' }
.control-sidebar-bg

app/views/admin/roles/_form.html.haml
= simple_form_for [:admin, @role] do |f|
  .container
    .row
      .col-lg-2
        = link_to admin_roles_path, 'data-position' => 'bottom', 'data-tooltip' => t('keppler.actions.back') do
          .arrow-back.btn.btn-default
            %i.icon-arrow-left
            = t('keppler.actions.back')

    .row
      .col-lg-12
        .box.slice-box.p-15
          .box-header.with-border
            %h3.box-title= t("keppler.modules.#{action_name.underscore}")
            .box-tools.pull-right
              %a.btn.btn-box-tool{ 'data-widget' => 'collapse', type: 'button' }
                %i.icon-minus
          .box-body
            %table.table.table-bordered
              %tbody
                .form-padding
                  .row
                    .col-xs-12
                      = f.input :name
                    .col-xs-12
                      .pull-right
                        = f.button :submit, t('keppler.actions.save'), name: '_save', class: 'btn-primary'

app/views/admin/roles/_listing.html.haml
- objects.each do |role|
  -# - unless role.name.eql?('keppler_admin')
  %tr{ id: "row-#{role.id}" }
    %td.item-check
      - if can?(Role).destroy_multiple?
        .checkbox
          %label{ for: "checkbox-#{role.id}" }
            %input{ type: 'checkbox', id: "checkbox-#{role.id}", 'checklist-model' => 'check', 'checklist-value' => role.id, '@click' => "listDelete(#{role.id})" }
            %span.cr
              %i.cr-icon.glyphicon.glyphicon-ok
      %td
        = link_to admin_role_path(role), title: t('keppler.actions.show') do
          %span
            = role.name
      %td{ style: 'width: 15px; padding-right: 15px;' }
        - unless role.id.eql?(1)
          = link_to admin_role_add_permissions_path(role.id), class: 'action-btn.pull-right' do
            %i.icon-settings
      %td{ style: 'width: 15px; padding-right: 15px;' }
        %a.action-btn.pull-right{ id: "menu-#{role.id}", 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown' }
          %i.icon-options-vertical
        %ul.actions.dropdown-menu{ 'aria-labelledby' => "menu-#{role.id}" }
          - if can?(Role).show?
            %li
              = link_to admin_role_path(role), title: t('keppler.actions.show') do
                %i.icon-eye
                = t('keppler.actions.show')
          - if can?(Role).update?
            %li
              = link_to edit_admin_role_path(role), title: t('keppler.actions.edit') do
                %i.icon-pencil
                = t('keppler.actions.edit')
          - if can?(Role).clone?
            %li
              = link_to admin_role_clone_path(role), title: t('keppler.actions.clone') do
                %i.icon-docs
                = t('keppler.actions.clone')
          - if can?(Role).destroy?
            %li
              = link_to admin_role_path(role), title: t('keppler.actions.delete'), method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
                %i.icon-trash
                = t('keppler.actions.delete')

app/views/admin/roles/_switch.html.haml
= simple_form_for @role, url: admin_role_create_permissions_path(role), method: :post, remote: true do
  %label.switch-box{ style: 'padding-top: 5px; padding-right: 40px;' }
    - if !role.action?(module_name, action)
      %label.switch
        %input{ name: 'role[module]', type: 'hidden', value: module_name }
        %input{ name: 'role[action]', type: 'hidden', value: action }
        - actions.each do |act|
          %input{ name: 'role[actions][]', type: 'hidden', value: act }
        %input{ id: "switch-#{module_name.split('::').join('')}-#{action}", type: 'checkbox' }
        %span.slider.round{ onclick: "sendPermission('#{module_name}', '#{action}')" }

    - else
      %label.switch
        %input{ name: 'role[module]', type: 'hidden', value: module_name }
        %input{ name: 'role[action]', type: 'hidden', value: action }
        - actions.each do |act|
          %input{ name: 'role[actions][]', type: 'hidden', value: act }
        %input.active{ id: "switch-#{module_name.split('::').join('')}-#{action}", type: 'checkbox', checked: 'checked' }
        %span.slider.round{ onclick: "sendPermission('#{module_name}', '#{action}')" }

:javascript
  function sendPermission(module_name, action) {
    $('#switch-'+module_name.split('::').join('')+'-'+action).parent().parent().parent().submit()
  }

app/views/admin/roles/edit.html.haml
= render 'form'

app/views/admin/roles/index.html.haml
#index-container{ controller: 'roles' }
  .container
    .row
      .listing.col-lg-12.col-xs-12
        %section.content-header.index-header
          %h1
            = t("keppler.modules.#{controller_path.underscore}")
          = entries(@total, @objects)
        %section.content-actions
          .toolbar
            .toolbar-item
              = link_to reload_admin_roles_path, class: 'tool-btn', remote: true do
                %i.icon-reload
            - if can?(Role).download?
              .toolbar-item
                = link_to admin_role_download_path(Role, format: :xls), class: 'tool-btn', title: t('keppler.actions.download_records') do
                  %i.icon-cloud-download
            - if can?(Role).upload?
              .toolbar-item
                = link_to '', class: 'tool-btn', title: t('keppler.actions.upload_records'), id: 'upload' do
                  %i.icon-cloud-upload
            .toolbar-item
              %a.tool-btn{ 'data-confirm' => t('keppler.messages.data_confirm'), 'data-method' => 'delete', 'v-bind:href' => 'link', :rel => 'nofollow', ':class' => '{disabled: !checks}' }
                %i.icon-trash
          .hide
            = form_tag admin_role_upload_path(@objects), id: 'upload-form', multipart: true, method: :post do
              = file_field_tag :file, id: 'upload-file'
          - if can?(Role).create?
            .add
              = link_to new_admin_role_path, class: 'btn-add' do
                +
                = t('keppler.actions.add')
        .box.slice-box
          .box-body.no-padding

            %table.table
              %thead
                - if @objects.size.zero?
                  %tr
                    %th.not-records.center
                      %h6= t('keppler.messages.not_found_records', model: t('keppler.models.pluralize.roles'))
                - else
                  %tr
                    %th
                      - if can?(Role).destroy_multiple?
                        .item-check
                          .checkbox
                            %label{ for: 'checkbox-all' }
                              %input{ type: 'checkbox', id: 'checkbox-all', '@click' => 'selectAll()' }
                              %span.cr
                                %i.cr-icon.glyphicon.glyphicon-ok

                    %th.hidden-xs
                      = sort_link(@q, :name) do
                        = t('activerecord.attributes.name')
                    %th
                    %th
              %tbody.objects-container{ 'data-update-url' => sort_admin_roles_path.to_s }
                = render 'admin/layouts/listing_preloader'
                = render 'listing', objects: @roles
        %center.paginator-module
          = paginate @objects, window: 1
  %aside.control-sidebar
    = render 'description', activities: @activities

app/views/admin/roles/new.html.haml
= render 'form'

app/views/admin/roles/reload.js.haml
$('.objects-container').html("#{j render 'listing', objects: @objects}");
$('.objects-container').css('opacity', '0');
$('.spinner2').css('display', 'block');
var request = $.ajax({url: "/admin/roles", method: "get", dataType: "html"});
request.done(function(msg){$('.spinner2').css('display', 'none');$('.objects-container').css('opacity', '1');});

app/views/admin/roles/show.html.haml
.container
  .row
    .col-lg-2
      = link_to admin_roles_path, 'data-position' => 'bottom', 'data-tooltip' => t('keppler.actions.back') do
        .arrow-back.btn.btn-default
          %i.icon-arrow-left
          = t('keppler.actions.back')

  .show-section
    .row
      .col-lg-12
        .box.slice-box.p-15
          .box-header.with-border
            %h3.box-title= t("keppler.modules.#{controller_path.underscore}")
            .box-tools.pull-right
              - if can?(Role).update?
                = link_to edit_admin_role_path(@role), class: 'btn btn-box-tool', title: t('keppler.actions.edit') do
                  %i.icon-pencil
              - if can?(Role).destroy?
                = link_to admin_role_path(@role), class: 'btn btn-box-tool', title: t('keppler.actions.delete'), method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
                  %i.icon-trash
          .box-body.box-body-no-padding
            %table.table
              %tbody
                - @role.as_json(only: %w[name]).each do |attribute, value|
                  %tr.list-row
                    %th.display-label= t("activerecord.attributes.#{attribute}")
                    %td.display-value.fs-body-1.tc-black-2
                      = value